# Application settings
spring.application.name=api
spring.profiles.active=dev

# Server settings
server.port=8080

# Datasource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/primeshoes
spring.datasource.username=snywy
spring.datasource.password=29042003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging settings
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
